### ISSUE TITLE
Connection was forcefully terminated by the host

### ISSUE THREAD

**Issue by Baaleos** [garry-edmonds/Tenon.Test.Client#1]
I discovered that when using .Net 4.6.2 with the Tenon Client, that my API calls were being terminated due to the host (tenon api website) not liking the version of Visual Studio was connecting with.

This can be resolved via adding:
`System.Net.ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;`

to the code before the http post request is sent.

**Comment by garry-edmonds** [comment]
Will update the code and add the security protocol's now used in .net 4.6.2.
Many thanks.
