### ISSUE TITLE
Http Post data needs to be form encoded

### ISSUE THREAD

**Issue by Baaleos** [garry-edmonds/Tenon.Test.Client#2]
Is there any chance of replacing your Execute Test code with something along the lines of

```
            HttpClient client = new HttpClient();
            var values = new Dictionary<string, string>
            {
               { "key", _key },
               { "src", _source }
            };
            var content = new FormUrlEncodedContent(values);
            var response = client.PostAsync("https://tenon.io/api/", content).Result;
            var responseString = response.Content.ReadAsStringAsync().Result;
            return JsonConvert.DeserializeObject<ApiResponse>(responseString);
```

Specifically the part around: 

> var values = new Dictionary<string, string>
>             {
>                { "key", _key },
>                { "src", _source }
>             };
>             var content = new FormUrlEncodedContent(values);

I discovered that when sending a large html page source - the Tenon Website was reporting incorrect results when sent via your client - eg: 1 result that complained that the page had no headings.
When the same page source was sent via Postman, it returned 14 issues.

I don't believe your client encodes the post data in the recommended fashion, which is why I was receiving incorrect results.

I corrected it by replacing my local copies execute test function with the code above.

**Comment by garry-edmonds** [comment]
Hi Baaleos, I will look at this and see about implementing what you have stated.  I no longer have an API key for Tenon.io so am unable to test the client.  So when I update it can you test this and let me know the outcome.

**Comment by garry-edmonds** [comment]
Have rewritten the client to use PostAsync method.  Hopefully will resolve your issue.  Version 1.0.2.
